apiVersion: v1
kind: Pod
metadata:
  name: load
  labels:
    app: load
spec:
  restartPolicy: Never
  enableServiceLinks: false
  containers:
    - name: load
      image: jp36/load:latest
      imagePullPolicy: Always
      ports:
        - name: metrics
          containerPort: 8000
          protocol: TCP
      env:
        - name: CPU_TARGET_PCT
          value: "30"
        - name: RAM_TARGET_MB
          value: "256"
        - name: NET_TARGET_MBPS
          value: "10"
        - name: NET_TARGET_HOST
          value: "iperf-server"
        - name: NET_TARGET_PORT
          value: "5201"
        - name: METRICS_PORT
          value: "8000"
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "1Gi"
