apiVersion: v1
kind: Service
metadata:
  name: load-metrics
  labels:
    app: load
spec:
  selector:
    app: load
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-metrics
  labels:
    app: load
    release: kps
spec:
  selector:
    matchLabels:
      app: load
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 9s
